blank_issues_enabled: false
contact_links:
  - name: è³ªå•ãƒ»ç›¸è«‡
    url: https://teams.microsoft.com/l/channel/19%3AmyiADQwuqHYv_IFfO6N5kSglPU-igrTGlvwWD9Cq5vg1%40thread.tacv2/%E4%B8%80%E8%88%AC?groupId=e65be845-c362-48b8-af50-da97a80bc724&tenantId=d19fb8bb-48e2-40cd-8357-ed6aba7e04df
    about: ãƒã‚°å ±å‘Šã‚„æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆä»¥å¤–ã®è³ªå•ãƒ»ç›¸è«‡ã¯Teamsã‚’ã”åˆ©ç”¨ãã ã•ã„ã€‚ï¼ˆæš«å®šï¼‰

# Issueä½œæˆæ™‚ã®ãƒ†ãƒ³ãƒ—ãƒ¬ãƒ¼ãƒˆè¨­å®š
defaults:
  - template: "bug_report.yml"
    name: "ğŸ› ãƒã‚°å ±å‘Š"
    about: "ãƒã‚°ã‚’å ±å‘Šã™ã‚‹"
  - template: "feature_request.yml"
    name: "ğŸ’¡ æ©Ÿèƒ½ãƒªã‚¯ã‚¨ã‚¹ãƒˆ"
    about: "æ–°æ©Ÿèƒ½ã®ã‚¢ã‚¤ãƒ‡ã‚¢ã‚’ææ¡ˆã™ã‚‹"
